<?php

namespace ContainerB7ECMir;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeniusServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\GeniusService' shared autowired service.
     *
     * @return \App\Service\GeniusService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/GeniusService.php';

        return $container->privates['App\\Service\\GeniusService'] = new \App\Service\GeniusService();
    }
}
