<?php

namespace ContainerB7ECMir;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLabelControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\LabelController' shared autowired service.
     *
     * @return \App\Controller\LabelController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/LabelController.php';

        $container->services['App\\Controller\\LabelController'] = $instance = new \App\Controller\LabelController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\LabelController', $container));

        return $instance;
    }
}
