<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Artist extends \App\Entity\Artist implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Artist' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Artist' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Artist' . "\0" . 'tapes', '' . "\0" . 'App\\Entity\\Artist' . "\0" . 'Archived', '' . "\0" . 'App\\Entity\\Artist' . "\0" . 'Suspended', '' . "\0" . 'App\\Entity\\Artist' . "\0" . 'cover', '' . "\0" . 'App\\Entity\\Artist' . "\0" . 'leakFiles'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Artist' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Artist' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Artist' . "\0" . 'tapes', '' . "\0" . 'App\\Entity\\Artist' . "\0" . 'Archived', '' . "\0" . 'App\\Entity\\Artist' . "\0" . 'Suspended', '' . "\0" . 'App\\Entity\\Artist' . "\0" . 'cover', '' . "\0" . 'App\\Entity\\Artist' . "\0" . 'leakFiles'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Artist $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Artist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getTapes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTapes', []);

        return parent::getTapes();
    }

    /**
     * {@inheritDoc}
     */
    public function addTape(\App\Entity\Tape $tape): \App\Entity\Artist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTape', [$tape]);

        return parent::addTape($tape);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTape(\App\Entity\Tape $tape): \App\Entity\Artist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTape', [$tape]);

        return parent::removeTape($tape);
    }

    /**
     * {@inheritDoc}
     */
    public function isSuspended(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSuspended', []);

        return parent::isSuspended();
    }

    /**
     * {@inheritDoc}
     */
    public function setSuspended(bool $suspended): \App\Entity\Artist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuspended', [$suspended]);

        return parent::setSuspended($suspended);
    }

    /**
     * {@inheritDoc}
     */
    public function isArchived(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isArchived', []);

        return parent::isArchived();
    }

    /**
     * {@inheritDoc}
     */
    public function setArchived(bool $Archived): \App\Entity\Artist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArchived', [$Archived]);

        return parent::setArchived($Archived);
    }

    /**
     * {@inheritDoc}
     */
    public function getCover(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCover', []);

        return parent::getCover();
    }

    /**
     * {@inheritDoc}
     */
    public function setCover(?string $cover): \App\Entity\Artist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCover', [$cover]);

        return parent::setCover($cover);
    }

    /**
     * {@inheritDoc}
     */
    public function getFullCoverPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullCoverPath', []);

        return parent::getFullCoverPath();
    }

    /**
     * {@inheritDoc}
     */
    public function getTapesByType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTapesByType', [$type]);

        return parent::getTapesByType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getAverageScore()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAverageScore', []);

        return parent::getAverageScore();
    }

    /**
     * {@inheritDoc}
     */
    public function getReviewCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReviewCount', []);

        return parent::getReviewCount();
    }

    /**
     * {@inheritDoc}
     */
    public function getLeakFiles(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeakFiles', []);

        return parent::getLeakFiles();
    }

    /**
     * {@inheritDoc}
     */
    public function addLeakFile(\App\Entity\LeakFile $leakFile): \App\Entity\Artist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLeakFile', [$leakFile]);

        return parent::addLeakFile($leakFile);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLeakFile(\App\Entity\LeakFile $leakFile): \App\Entity\Artist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLeakFile', [$leakFile]);

        return parent::removeLeakFile($leakFile);
    }

}
