<?php

namespace ContainerBadr8TX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFTPServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\FTPService' shared autowired service.
     *
     * @return \App\Service\FTPService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/FTPService.php';

        return $container->privates['App\\Service\\FTPService'] = new \App\Service\FTPService();
    }
}
