<?php

namespace ContainerVwZxJN6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MGVGY2GService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mGVGY2G' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mGVGY2G'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ftpservice' => ['privates', 'App\\Service\\FTPService', 'getFTPServiceService', true],
            'genius' => ['privates', 'App\\Service\\GeniusService', 'getGeniusServiceService', true],
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
            'tape' => ['privates', '.errored..service_locator.mGVGY2G.App\\Entity\\Tape', NULL, 'Cannot autowire service ".service_locator.mGVGY2G": it references class "App\\Entity\\Tape" but no such service exists.'],
        ], [
            'ftpservice' => 'App\\Service\\FTPService',
            'genius' => 'App\\Service\\GeniusService',
            'managerRegistry' => '?',
            'tape' => 'App\\Entity\\Tape',
        ]);
    }
}
