<?php

namespace ContainerVwZxJN6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1TqAO3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1Tq_AO3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1Tq_AO3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'fileService' => ['privates', 'App\\Service\\LeakFileService', 'getLeakFileServiceService', true],
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'fileService' => 'App\\Service\\LeakFileService',
            'managerRegistry' => '?',
        ]);
    }
}
