<?php

namespace ContainerVwZxJN6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLabelService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.EnhlBww.App\Entity\Label' shared service.
     *
     * @return \App\Entity\Label
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.EnhlBww": it references class "App\\Entity\\Label" but no such service exists.');
    }
}
