<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVwZxJN6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVwZxJN6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVwZxJN6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVwZxJN6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVwZxJN6\App_KernelDevDebugContainer([
    'container.build_hash' => 'VwZxJN6',
    'container.build_id' => '7fdbc146',
    'container.build_time' => 1673039249,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVwZxJN6');
