<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCn6fe4a\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCn6fe4a/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCn6fe4a.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCn6fe4a\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCn6fe4a\App_KernelDevDebugContainer([
    'container.build_hash' => 'Cn6fe4a',
    'container.build_id' => '6c19bebf',
    'container.build_time' => 1673045793,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCn6fe4a');
